### ISSUE TITLE
does not work with 1.18.1?

### ISSUE THREAD

**Issue by ducky0** [TheBreakery/Bloomware#55]
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'bloomware'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: Cannot invoke "me.offeex.bloomware.client.module.Module.setEnabled(boolean)" because the return value of "me.offeex.bloomware.client.module.ModuleManager.getModule(String)" is null
	at me.offeex.bloomware.Bloomware.onInitializeClient(Bloomware.java:99)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more

**Comment by DiOnFire** [comment]
Currently, the jar file for version 1.18.1 is not ready yet, but Bloomware has already been ported to the new version. The latest jar file in the releases is made for version 1.16.5.

**Comment by ducky0** [comment]
> Currently, the jar file for version 1.18.1 is not ready yet, but Bloomware has already been ported to the new version. The latest jar file in the releases is made for version 1.16.5.

i built the 1.18.1 source from the github and it still crashes

**Comment by cPyrobyte** [comment]
> > Currently, the jar file for version 1.18.1 is not ready yet, but Bloomware has already been ported to the new version. The latest jar file in the releases is made for version 1.16.5.
> 
> i built the 1.18.1 source from the github and it still crashes

Same here
